### ISSUE TITLE
Downpatrick missing

### ISSUE THREAD

**Issue by HyperFail** [4A47/liveodds#2]
Hello there,

There doesn't appear to be any odds being pulled for Downpatrick when passing in for IRE. For example Wexford is returned for 2021-05-21 but Downpatrick races are missing.
[https://www.racingpost.com/racecards/179/downpatrick/2021-05-21/785398/](https://www.racingpost.com/racecards/179/downpatrick/2021-05-21/785398/)

**Comment by 4A47** [comment]
Didnt realise they had Northern Ireland tracks separate from Ireland, sorted now. Cheers.
