### ISSUE TITLE
error on odds retrieval

### ISSUE THREAD

**Issue by HyperFail** [4A47/liveodds#3]
Hello 4A47,

Looks like attempting to pull odds is resulting in the below error.

`price = float(tag_with_attrib(row, '/td', f'data-bk="{book}"').attrib['data-odig'])
AttributeError: 'NoneType' object has no attribute 'attrib'`

**Comment by 4A47** [comment]
can you post your code thats failing

**Comment by HyperFail** [comment]
`from liveodds.racing import Racing

racing = Racing()

today = racing.dates()[1]

json = racing.meetings_json(today, 'UK')`

**Comment by 4A47** [comment]
should be working now

and racing.dates()[1] will get tomorrows date, 0 for today

**Comment by HyperFail** [comment]
Thanks @4A47, I will try it this evening and let you know. Thanks for prompt response.

**Comment by HyperFail** [comment]
@4A47, it's working now. Thanks for sorting.
