### ISSUE TITLE
Oddschecker - website change

### ISSUE THREAD

**Issue by gbettle** [4A47/liveodds#4]
I think from today Oddschecker have updated their website.

When:

racing = Racing()
print(racing.dates())

Output: 
[] 

NULL is now returned

**Comment by 4A47** [comment]
Might have been a temporary issue on the site, working fine right now.

**Comment by gbettle** [comment]
Grrr ... so sorry. It must be a change on my side in my network. 

Many thanks - G.

**Comment by 4A47** [comment]
No probs, I have not tested this on windows so could be some issues there.
